- package-lock.json
- package.json
- src/data/example.json
- src/index.ts
- src/lib/imageCreator.ts
- src/lib/scope2.handlebars
- src/lib/scope3.handlebars
- src/prompts/parsePDF.ts
- src/prompts/reflect.ts
- src/workers/discordReview.ts
Show a table with json output as image in Discord according to Alexandras best example on how to make an overview over CO2 emissions data.
Solves: #25
> CO2 table image

- src/workers/downloadPDF.ts
- src/workers/parseText.ts
- src/workers/reflectOnAnswer.ts
- src/workers/userFeedback.ts
Den här löser problemet med Swedbank och Astra Zeneca genom att vi har en egen user header:
```
const response = await fetch(url, {
headers: {
'User-Agent': 'Garbo/1.0 (Linux; OpenAI 4;) Klimatkollen',
},
})
```
Solves: #64
> Fix for restricted websites

- README.md
- k8s/worker.yaml
- src/config/discord.ts
- src/discord.ts
- src/discord/commands/pdfs.ts
This PR aims to solve the problem when multiple workers acknowledge the interaction at the same time resulting in worker restart. This will hopefully solve some of the instability issues we have seen where some of the jobs are stalling.
> fix: only handle commands and interactions from one instance

- src/workers/extractEmissions.ts
- src/workers/followUp.ts
- src/workers/reflectOnAnswer.ts
- src/workers/userFeedback.ts
> feat: use gpt4o instead- faster and better

- src/data/ica.json
- src/discord/commands/index.ts
- src/discord/commands/json.ts
Add /json as command to be able to grab the actual json from a thread.
> feat: json command

- src/prompts/extractJson.ts
The prompt asks for data, this is to also reflect this info in the json
> Adding number of employees to json

- package-lock.json
- src/data/example.json
- src/discord/commands/facit.ts
- src/lib/discordTable.ts
- src/lib/facit.ts
- src/models/companyEmissions.ts
- src/opensearch.ts
- src/prompts/followUp/scope12.ts
- src/workers/discordReview.ts
We change from using this format
```
{
companyName: 'Example AB',
emissions: [
{ "year": 2023 ...}
]
```
To:
```
{
companyName: 'Example AB',
emissions: {
2023: { "year": 2023 ...}
}
```
> fix: change from array to object for emissions object

- src/prompts/extractJson.ts
- src/prompts/feedback.ts
- src/prompts/followUp/goals.ts
- src/prompts/followUp/publicComment.ts
- src/prompts/parsePDF.ts
Solves #135 
**Tone**: Try to be neutral and informative. If you see something that seems off, mention it in the public comment. Our goal is to push the companies we review to be both better at reporting and also to be better at
reducing their emissions so if you find something good, mention that as well. Your name is Garbo and you are allowed to have a personality but always be professional.
*** LANGUAGE: ONLY WRITE IN SWEDISH! *** 
Example (replace with actual data):
> Example AB rapporterar överlag en heltäckande rapport av sina egna utsläpp. Däremot har man antagligen utelämnat en hel del utsläpp i Scope 3 från kategorierna Inköpta varor och tjänster som bör vara en betyande del av den här typen av företags utsläpp. Nedströms transport och distribution (9) och Användning av sålda …
> Snazzy swedish garbo now speaks swedish

- src/prompts/format.ts
- src/prompts/reflect.ts
- src/workers/format.ts
> feat: include the process description

- src/discord.ts
- src/prompts/reflect.ts
- src/workers/discordReview.ts
- src/workers/reflectOnAnswer.ts
If we merge this - Garbo will be more focused on the end result, not as much on the intermediate results
> fix: make her speak less

- .env.example
- README.md
Also fix a faulty DB name to match the production environment.
> Docs: Describe how to restore local DB backups

- src/prompts/followUp/industry_gics.ts
> Clarify gics extraction to use 8 digits for the subIndustryCode

- .github/workflows/ci.yml
- .github/workflows/production.yml
> chore: Bump GitHub action versions

- src/lib/pdfTools.ts
> Avoid table screenshot name collisions by using random ID

- src/prompts/followUp/industry_gics.ts
- src/workers/followUp.ts
- src/workers/nlmParsePDF.ts
This pull request includes changes to the `src/workers` directory to improve the handling of job data and optimize the `nlmParsePDF` worker. The most important changes include removing the `json` property from the `JobData` class and ensuring that the `json` representation of the report is no longer needed after parsing.
Improvements to job data handling:
* [`src/workers/followUp.ts`](diffhunk://#diff-853e7d059e753c432795c25aff79cb792beab4d69e43f715d2f4aba840f5c84eL14): Removed the `json` property from the `JobData` class, as it is no longer required.
Optimizations to `nlmParsePDF` worker:
* [`src/workers/nlmParsePDF.ts`](diffhunk://#diff-c058c1bae0c644ebe0d37428b23679ce64f4063111b9a8c1e1c5b3cc441c6a24R70-R74): Updated the `nlmParsePDF` worker to set the `json` property to `undefined` …
> Bugfix release: increase speed in bull dashboard

- package.json
- src/lib/jsonExtraction.ts
- src/lib/pdfTools.ts
- src/workers/nlmExtractTables.ts
- src/workers/saveToAPI.ts
This pull request includes several changes to improve the handling of PDF table extraction and processing, as well as some minor refactoring and bug fixes. The most important changes include modifications to table extraction logic, enhancements to search functionality, and improvements to the `saveToAPI` worker.
* [`src/lib/pdfTools.ts`](diffhunk://#diff-01400b53c974967e36d5d7b869071077cb0181dbed19d67f6b0505e2d49d207aL116-R134): Modified `extractTablesFromJson` to handle multiple search terms, track unique pages, and return tables with filenames. [[1]](diffhunk://#diff-01400b53c974967e36d5d7b869071077cb0181dbed19d67f6b0505e2d49d207aL116-R134) [[2]](diffhunk://#diff-01400b53c974967e36d5d7b869071077cb0181dbed19d67f6b0505e2d49d207aL133-R165)
* …
> Release 3.3.0

- src/workers/saveToAPI.ts
This pull request introduces significant changes to the `scope3.ts` file to improve the clarity and structure of the prompt for extracting scope 3 emissions. The most important changes include restructuring the prompt instructions, updating the categories, and specifying the output format.
Changes to prompt instructions and structure:
* The prompt has been restructured to include clear sections with headings such as "Scope 3", "Instructions", "Reporting Categories", "Missing Or Incomplete Data", "Units", "Financial Institutions", "Totals", "Transportation Categories", and "Output Format". This improves readability and ensures that each instruction is easily identifiable.
Updates to categories and data handling:
* The GHG categories have been explicitly listed within the prompt, ensuring …
> Release: scope 3 consistancy

- package-lock.json
- package.json
> Add optional dependencies for sharp to package-lock to hopefully fix error

- package-lock.json
- package.json
This pull request includes changes to the `package.json` file to update dependencies. The most important changes include the addition of a new package and the removal of a redundant entry.
Dependency updates:
* Added `dotenv-cli` version `^7.4.4` to the dependencies section.
* Removed redundant `dotenv-cli` entry from the dependencies section.
> Fix production issues

- src/lib/vectordb.ts
- src/workers/indexMarkdown.ts
- src/workers/nlmExtractTables.ts
🩹 Fix so chunk size doesnt exceed chroma limit
> fix chunking error

- Dockerfile.base
- Try to upgrade version of gm to the one running locally ( version 1.3.45-r0 )
> Use newer version of gm

- Dockerfile
This is in order to use latest version of gm package
> Update docker file to run on alpine edge

- src/prompts/followUp/economy.ts
👍 There where a confusion example on how to deal with units and currency.
👍 Now it is more clear with examples on how to convert to base unit and report currency
> Improve economy prompt for units conversion and currency

- src/workers/saveToAPI.ts
Diff similar structure to allow saving `economy` data even if nothing has been saved before (#380)
* Transform before and after to a similar structure for more accurate diffs
This will hopefully fix an issue preventing economy data from saving as expected.
* Only diff array fields for actual changes
Also change order to be consistent.
> Release to production

- src/workers/guessWikidata.ts
- src/workers/precheck.ts
- src/workers/sendCompanyLink.ts
- Log garbo's wikidata guess to Discord
- Stricter prompt to avoid marketing language in `description`
- Use correct frontend base URL in `sendCompanyLink`
> Release bug fixes to production

- src/discord/interactions/approve.ts
- src/lib/prisma.ts
- src/lib/wikidata.ts
- src/workers/guessWikidata.ts
- tests/prisma.test.ts
🟢 The approve button was missing the wikidataId rendering it useless
> Fix approve button

- scripts/import-spreadsheet-companies.ts
- scripts/import.ts
- src/lib/prisma.ts
- src/routes/readCompanies.ts
- src/routes/updateCompanies.ts
- Update import script
- Add `scope1And2` to API
- Improve handling of scope 3 `categories`
- Fix tags
> Prepare import script and API for mid cap release

- scripts/import-spreadsheet-companies.ts
- src/routes/readCompanies.ts
> Fix: Remove unwanted (e.g. duplicate, invalid wikidataId) companies from the API

- src/routes/readCompanies.ts
fix #456
This should make the numbers look and feel much more accurate.
> Account for `scope3.statedTotalEmissions` and `scope1And2.total` when preparing `calculatedTotalEmissions`

- src/lib/prisma.ts
- src/routes/updateCompanies.ts
- Almost ready just need some more testing
> Feat: Fix deletion ability for scope1, scope2, scope1and2

- src/lib/prisma.ts
- src/routes/updateCompanies.ts
- This is important for our cleanup and editor
- However during this PR some questionable logic was found demanding a fix: #478 
- This led to a temporary fix to make sure that the statedTotalEmission id is there ( will be cleaner after 478 )
> Feat: Make totalStatedEmissions deletable

- src/lib/prisma.ts
- src/routes/updateCompanies.ts
- Feat: Make totalStatedEmissions deletable (#479)
> Update garbo production

- src/lib/prisma.ts
- src/routes/updateCompanies.ts
- Need to be able to remove faulty economy data
- Cleaned-up the update + create logic ---> upsert
> Feat: Deleting economy data working

- src/routes/readCompanies.ts
Feat/minimal list data (#505)
* Remove tags since we currently no loger use them
* Remove dataOrigin from metadata since its currently unused
* Remove GICS translation strings from list API response
* Remove goals and initiatives from list API response
* Use minimal metadata for list API response
> Release garbo to production

- package-lock.json
- package.json
This fixes the production build
> Add missing dependencies that were installed as devDependencies by mistake

- package.json
- prisma/migrations/20250113142336_remove_old_structure/migration.sql
- prisma/migrations/20250113153942_update_name/migration.sql
- prisma/migrations/20250113160200_move_data/migration.sql
- prisma/migrations/20250113162855_remove_tmp_tables/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- scripts/add-gics.ts
- scripts/migrateDataToNewSchema.ts
- src/api/routes/company.read.ts
Tested locally on production data, and with `prisma migrate deploy` to match behaviour in production.
Feat/finish migration (#549)
> Deploy migrations to production

- src/api/routes/company.read.ts
🐛 Noticed that the refresh did not behave as intended after additions 
👓 The problem was that the metadata.updatedAt was not compared correctly
🌍 With this fix it correctly compares that part and makes sure to re-query companies when new metadata is present
> Fix-e-tags-for-additions

- src/prompts/followUp/economy.ts
🌍 Updated employee unit handling in Garbo:
•	Added other acceptable units (e.g., AVG, EOY) to avoid faulty usage of FTE.
•	Clarified instructions to set the unit to null if no unit is specified.
Closes #383  
Closes #463
> Fix employee units

- README.md
- docker-compose.yaml
Added a docker compose file to simplify container startup. Updated readme accordingly.
> Feat: Added docker compose file

- src/api/args.ts
- src/api/schemas/response.ts
Fixes #613 
- Updated response body schema for getting all companies
- Updated db get arguments to include tags
> feat: tags are now included when fetching a list of all companies

- README.md
- eslint.config.mjs
- k8s/overlays/production/kustomization.yaml
- k8s/overlays/staging/kustomization.yaml
- package-lock.json
- package.json
- src/api/plugins/auth.ts
- src/api/routes/company.read.ts
- src/api/schemas/common.ts
- src/api/schemas/response.ts
- src/api/services/companyService.ts
- src/createCache.ts
- src/discord.ts
- src/lib/DiscordWorker.ts
- src/lib/jsonExtraction.ts
- src/lib/openai.ts
- src/lib/pdfTools.ts
- src/lib/saveUtils.ts
- src/lib/wikidata.ts
- src/workers/checkDB.ts
- src/workers/diffBaseYear.ts
- src/workers/diffGoals.ts
- src/workers/diffInitiatives.ts
- src/workers/followUp.ts
- src/workers/guessWikidata.ts
- src/workers/nlmExtractTables.ts
- src/workers/nlmParsePDF.ts
- Added eslint to the project (will only warn for now)
- Fixed various errors (any types, unused variables)
- Fixed small style error in the readme
> Feat: Added Eslint support and fixed regarding code issues

- src/lib/api.ts
> Added method to check if token is expired

- src/api/schemas/response.ts
- src/data/climate-data.json
Replace 1e10 with null values for municipalities without public charging points
> Update charging point data to include null values

- src/data/climate-data.json
Update muncipality consumption emissions with entry for 2022
> Feat update municipality consumption emissions with new entry

- src/data/climate-data.json
Upgrade from 2022 to 2023 year data for municipality consumption emissions
> [feat] update municipality consumption emissions with 2023 entry

- src/api/routes/validation.read.ts
- src/api/routes/validation.update.ts
- src/api/schemas/request.ts
- src/api/schemas/response.ts
- src/api/types.ts
- src/app.ts
- src/config/openapi.ts
Draft PR to add API to manage validation claims.
> Add validation claim support

- src/api/schemas/response.ts
> Made descriptions property optional in response

- package-lock.json
- package.json
_Select the appropriate release type by marking with an `x`._
- [x ] Major version bump
- [] Minor version bump
v.3.20.1
This release promotes changes **from `stage` to `production`**.
_Provide a summary of the features, fixes, or updates included in this production release._
- emissions assessment routes
- company descriptions in get companies
- industry code routes
- [ x] All relevant changes have been QA-tested in staging
---
_This template is for versioned production releases only. For other PR types, please select a different template._
> [Prod] Major Version Bump v4.0.0

- k8s/base/api.yaml
- src/config/api.ts
> Fixed env variables in staging/prod
