Klimatbyran/garbo

README.md
Elastic variables have been added to the README since they are needed in the .env file.
=> Add Elastic environment variables to README

Dockerfile
We need chromium installed to be able to use it through pupeteer.
=> fix: add chromium dependencies

src/prompts/parsePDF.ts
Instead of allowing Garbo to choose between LB and MB when both are available, always opt for MB.
=> Make MB default scope 2 selection

src/prompts/parsePDF.ts
Some companies report negative emissions from CO2 "savings", or report total values that are adjusted with the use of carbon offsets. This addition to the prompt tells Garbo to not include these reductions, since reporting on them is not in line with the GHG Protocol guidelines.
=> Exclude negative emissions and offsets

src/prompts/parsePDF.ts
Many companies report on categories or emission sources that are either not perfectly aligned with the GHG-protocol, or don't sum all sub-categories. This addition to the prompt tells Garbo to find and present all emissions, also those that are not clearly identifiable as Scope 1, 2, 3 or match with the pre-defined Scope 3 categories.
=> Identify other emissions

src/workers/pdf2Markdown.ts
This PR solves `TypeError: Cannot read properties of null (reading 'length')` which was triggered in at least one instance at http://localhost:3000/admin/queues/queue/pdf2Markdown/93?status=failed
It seems like `completed` jobs can still get `null` as their return value. It might be a symptom of previous jobs not finishing as expected.
Looking at the error from above, the input data looks odd. According to the type definition at https://github.com/Klimatbyran/garbo/blob/543c3bf54e7aeb6500f825fdd131b7063f1daf61/src/workers/pdf2Markdown.ts#L104, `existingId` should always be a string, but as you can see in the screenshot below, it's `undefined`.
This is what caused the original error.
=> Ensure previous job was successful and returned actual data

src/discord/commands/list.ts, src/elastic.ts
When pressing Retry or Feedback on any company on the list we want to create new jobs so we can manually check each company we publish and add feedback based on new information we get.
=> feat: WIP add buttons for retry, feedback to each element on list

src/prompts/followUp/goals.ts
Fix #144 
This was mostly already resolved, but the prompt formatting could be improved to make it consistent with `initiatives`.
=> Fix #144 - Update goals prompt and clarify to use climate goals

src/lib/DiscordWorker.ts, src/lib/vectordb.ts, src/workers/followUp.ts, src/workers/indexMarkdown.ts, src/workers/nlmParsePDF.ts
This simplifies the worker code interacting with the vector DB.
NOTE: I opted to let `vectorDB.addReport()` accept both `markdown` and `paragraphs` as parameters, rather than just `markdown`. The reason is that it made more sense to log the number of paragraphs in the `indexMarkdown` worker. One more parameter to the `addReports()` method is worthwhile since it makes the code much more readable, logging the number of paragraphs before we attempt to save to the vector DB.
=> feat: Add a wrapper lib around our vector DB to simplify the code and future updates

src/lib/vectordb.ts, src/workers/indexMarkdown.ts
✂️ Previously we divided chunks by "###n" (header sections)
✂️ With this approach we divide the text into chunks of 1000 characters with 200 character overlap
📈 From my experiments the results where substantially better with this method
Ex:
Tried a few more as well. Here it is 100% https://www.add.life/media/nwepx4r4/addlife-annual-report-2023.pdf
fixes #282
=> Update chunking strategi

k8s/api.yaml, k8s/pre-deploy/db-migrate.yaml, k8s/worker.yaml, package.json
This pull request includes updates to the image version and the package version for the `garbo` application. The primary changes are as follows:
Version updates:
* [`k8s/api.yaml`](diffhunk://#diff-dd30f0e817cb2c8d2badae6c4a416547cc48d9f33fdfd3c358c1640975211631L17-R17): Updated the `garbo` image version from `3.1.20` to `3.1.23` in the `spec` section.
* [`k8s/pre-deploy/db-migrate.yaml`](diffhunk://#diff-b7e3098f6f4d46b0fc9caf497c010722437197fa07654596153aa41dba43776eL12-R12): Updated the `garbo` image version from `3.1.20` to `3.1.23` in the `spec` section.
* [`k8s/worker.yaml`](diffhunk://#diff-93e545542bd6994776e508e6d47317afdf317ae9b8fdf9dc82b77dc426d3f17bL17-R17): Updated the `garbo` image version from `3.1.20` to `3.1.23` in the `spec` section.
* …
=> Sync staging with main

src/lib/jsonExtraction.ts, src/lib/pdfTools.ts, src/workers/nlmExtractTables.ts
🔍 It would be great if we could find more relevant tables to search with openAI vision. 
🔍 In this implementation we extend the table searchterm --> searchTerms and look through thoose
🔍 However because of a bugg we currently send a picture of the entire page to openAI, this is not something we want to do for tables that are on the same page. I feel that this implementation wasn't super readable so not quite happy with it yet. Would like to simplify. But the ideá / problem is interesting. "How do we send the right data to visonAPI". 
⚙️ Leaving this up as a draft for know. Look forward to discussing 
This relates to issue #260 but I am not confident in the results yet
Fix #260
=> Extend tables sent to openai vision

src/prompts/followUp/scope3.ts
This pull request includes significant updates to the `prompt` in the `scope3.ts` file to improve clarity and ensure consistent reporting of scope 3 emissions according to the GHG Protocol. The changes focus on restructuring the instructions and refining the output format.
Key changes include:
* The `prompt` has been restructured into a more organized format with clear sections and instructions. This includes adding headings and numbered instructions to enhance readability and comprehension.
* Added specific guidelines for reporting categories, handling missing or incomplete data, and converting units to metric tons of CO2 equivalent.
* Included instructions for financial institutions to look for emissions data related to investments and portfolios, which may be found in different …
=> fix: more consistant prompt for scope 3

src/prompts/followUp/scope3.ts
This pull request includes a change to the `src/prompts/followUp/scope3.ts` file to clarify the conversion of units for emissions reporting.
* [`src/prompts/followUp/scope3.ts`](diffhunk://#diff-7584de0ff77df58814bb0358e42151ba15bde81d71ce2259377e659e1506373aL54-R54): Updated the instructions to specify that kton (1000 tCO2) and Mton (1000000 tCO2) should be converted to metric tons of CO2 equivalent.
=> fix: explicit kton unit conversion

package-lock.json, src/lib/vectordb.ts, src/workers/indexMarkdown.ts, src/workers/nlmExtractTables.ts
🎸 Fix chroma range error bugg
🎸 improved reduce funciton to vision api
Fix #276
=> Bring back section chunking

src/lib/DiscordWorker.ts
The root cause was related to something else and not the lack of a return value from the job
=> DX: Allow any return from DiscordWorker processor function.

package.json, scripts/dev-reset.ts, src/lib/dev-utils.ts, src/lib/vectordb.ts, src/routes/readCompanies.ts, src/workers/nlmExtractTables.ts
Simplify local development when testing reports and resetting especially `chroma` and `redis`
Fix #264
=> Add dev-reset script

.github/workflows/base-image.yml, Dockerfile.base
This pull request includes changes to the `Dockerfile` and `Dockerfile.base` to update the base image and add necessary dependencies for the application. The most important changes include switching the base image to `node:alpine` and adding various development packages.
Changes to `Dockerfile`:
* Switched the base image from `ghcr.io/klimatbyran/garbo-base:main` to `node:alpine`.
* Added multiple development packages such as `chromium`, `nss`, `freetype`, `python3`, `make`, and others to support the application dependencies.
Changes to `Dockerfile.base`:
* Added `ghostscript-dev` and `graphicsmagick-dev` to the list of installed packages.
=> Release without base image

k8s/worker.yaml, src/workers/saveToAPI.ts
The workers are not restarting on build --> might have to do with resource demand in yaml file added yesterday. Trying to remove it and se if it resolves
=> Update workers yaml to remove resource demand, and trigger rebuild

src/routes/updateCompanies.ts, src/workers/nlmParsePDF.ts
This should reduce reduce the size of the job data, and reduce storage and memory required for the queue.
Follow up for https://github.com/Klimatbyran/garbo/pull/302 - it seems like that change got lost somewhere when merging staging and main.
=> Only pass parsed json data explicitly when needed, and remove from other jobs

src/workers/saveToAPI.ts
This fixes the two diffing-bugs - 1) not possible to save `economy` data and 2) inaccurate and unreliable diffs for `emissions` - introduced last week. However, the code should probably be cleaned up a bit.
I'm considering transforming the `[before, after]` data in the beginning of the worker, so we can make the diff against the same data as we later save. This would also have the benefit of simplifying the process of saving each data point, since we could refactor this worker to only do the structural data transformation to match the API expectations in one place at the start.
=> Diff similar structure to allow saving `economy` data even if nothing has been saved before

src/workers/nlmParsePDF.ts
When we try to retry because of a previous failure, the error gets rethrown as an UnrecoverableError which means it will not try again. This PR solves that problem.
Error handling improvement:
* [`src/workers/nlmParsePDF.ts`](diffhunk://#diff-c058c1bae0c644ebe0d37428b23679ce64f4063111b9a8c1e1c5b3cc441c6a24L128-R128): Changed the thrown error from `UnrecoverableError` to `Error` in the `catch` block for better general error handling.
=> fix: retrying doesn't work if we use UnrecoverableError

src/lib/prisma.ts, src/routes/updateCompanies.ts
- We have a problem with scope 3 categories being set to zero when faulty (due to no option to delete them at the moment)
- Solution, allow to purposely have a scope3Cat total as null which will result in a delete of that category.
=> allow null for scope 3 categories in order to delete them

src/lib/prisma.ts, src/routes/readCompanies.ts, src/routes/updateCompanies.ts
- Add `id` for `initiatives` and `goals` to allow updating and deleting data.
- Allow deleting `scope1`, `scope2` and `scope1And2` to unset values.
=> Update garbo production

src/lib/prisma.ts, src/routes/updateCompanies.ts
=> Fix #493 - Allow setting individual `scope2` values to `null` to get correct calculations of total emissions

src/routes/readCompanies.ts
* Fix #498 - Only return `emissions` for a reportingPeriod if it includes actual data
* Fix #487 - Only include properties if they have data, and otherwise exclude them from the response
* Also remove empty values for scope 3 categories
=> Fix/dont return empty emissions for reporting period (#499)

src/routes/readCompanies.ts
This fixes a calculation bug for `scope2.calculatedTotalEmissions`
=> Prioritise mb over lb for scope 2

src/api/routes/company.industry.ts, src/prompts/followUp/scope3.ts, src/workers/nlmExtractTables.ts
🌍 Scope3 categories was only defined by word and garbo could use better information on what they really mean
🌍 Giving each category a bit of a definition and clearly separating what is upstream and downstream
👏 Big thanks to Alex for helping out with these definitions ⭐ 
📈 Another significant improvement is instructing our vision-GPT to consistently use placeholders like “n.a.” for any missing cells or values in tables. This ensures table alignment and prevents values from shifting into incorrect categories, which can otherwise lead to misinterpretations or inaccuracies. Previously, many cases where we assumed Garbo was not ready for calculations were actually due to misplaced values caused by gaps in the data. This change greatly enhances the reliability and accuracy of extracted table …
=> Improve scope3 categories and table reading

src/api/routes/municipality.read.ts
🌍 Let’s optimize data transfer by implementing an ETag for the getAllMunicipalities route.
🌍 Since the data is currently static, a simple static ETag without any time restriction should suffice for now.
🌍 In the future, when municipalities are stored in the database, we can revisit this and implement dynamic ETag generation based on data changes.
=> Static e-tag for municipalities

README.md, package-lock.json, package.json, src/api/routes/company.delete.ts, src/api/routes/company.read.ts, src/api/routes/municipality.read.ts, src/api/schemas/response.ts, src/createCache.ts, src/index.ts
🌍  This PR introduces Redis-based caching for better performance and reduced database load.
Key Updates:
🌍 Companies API: 
- Implements Redis cache with dynamic keys tied to latestMetadataUpdatedAt.
- Reduces redundant database queries by serving cached data when available.
🌍 Municipalities API:
- Adds Redis cache with a static key since data is immutable.
- Enhances performance with faster responses for repeated requests.
Benefits:
🌍 Optimized server performance.
🌍 Simplified cache management with automatic invalidation for updates.
🌍 Scalable design leveraging Redis.
🏠 Updated the readme with a quick setup for redis insight. Where you can inspect you redis data 
Testing:
✅ Verified caching works for /companies and /municipalities APIs.
✅ Ensured no impact on existing ETag …
=> Add redis caching

src/api/routes/company.read.ts
🌍 Updated calculatedTotalEmissions logic to exclude Scope 3 Category 16 (other) unless verified, ensuring invisible numbers do not affect calculations.
Closes #527
=> Exclude Scope 3 Category 16 Emissions Unless Verified

src/api/schemas/common.ts, src/api/schemas/request.ts, src/api/services/companyService.ts, src/api/services/emissionsService.ts, src/prompts/followUp/biogenic.ts, src/prompts/followUp/scope12.ts, src/prompts/followUp/scope3.ts
🌍 Updated schema to support both tCO2e (preferred) and tCO2 as valid units for emissions reporting.
🌍 Ensured tCO2 is only used when explicitly reported without the “e” suffix.
🌍 Included unit conversion for tCO2 and tCO2e to ensure all values are consistently reported in metric tons.
Closes #533 
Closes: #569
=> Add enum option to support tCO2 when tCO2e suffix is not available

src/api/services/metadataService.ts
Fixes an issue in the updating/creating of reporting periods
As the email is not a unique identifier anymore, the creation of verified metadata failed, blocking the whole reporting period upsert.
Fix: Switched the use of email in the creation of verified metadata with the user id.
=> [Fix] Changed verified metadata to use user id instead of the email

src/api/args.ts, src/api/schemas/response.ts
This is a fix to allow responses to contain a description with null value, when doing a Http Get request for companies.
=> Made description nullable in schema

src/lib/openai.ts
i dont really see the point of supporting json_object as return value from openai, we always send a real schema instead
=> removing the json object default since we always send in the schema

jest.config.js, package-lock.json, package.json, src/lib/jsonExtraction.ts, src/lib/tableParser.ts, tests/json-table-to-markdown.spec.ts
After nlm-ingestor has parsed the whole pdf and created a json, we pass the tables from the json data to our own function that transforms those tables into markdown format.
It worked well for tables that just had years as headers, but not for a table like the one below that has double headers. First a 'grouping' header that tells us which columns are retrospective or not and only below it are the years..
😱  if the years were only the second header we didn't include that header at all in the markdown, meaning we lost all the year columns..
👉  markdown renderers don't often support double headers on tables so now I added logic that tries to find the most relevant header by prioritizing headers that contain years or that has more unique values across columns. Other headers are added as a …
=> Table to markdown improvements

src/api/routes/municipality.read.ts
Add version to municipality cache key to make it refresh when new version of app is deployed.
=> [fix] add version to municipality cache key
